version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: exam_mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: exam_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: exam_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
