name: CI/CD Exam Cloud

on:
  push:
    branches:
      - main

jobs:
  backend:
    name: Backend - install, audit, test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Audit dependencies
        run: npm audit --audit-level=high
        continue-on-error: true

      - name: Run tests
        run: npm test -- --watchAll=false
        continue-on-error: true

  frontend:
    name: Frontend - install, audit, build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Audit dependencies
        run: npm audit --audit-level=high
        continue-on-error: true

      - name: Build React app
        run: npm run build